/*
===============================================================================
                        MATRIX ENGINEERING TOOL
===============================================================================

Author      : Muhammad Ali Haider
Project     : Matrix Engineering Tool
Language    : C
Compiler    : GCC (Rev11, Built by MSYS2 project) 15.2.0
IDE         : Visual Studio Code 1.133.0
Date        : August 14, 2026

Description :
    A menu-driven matrix calculator developed in C.

    The program supports:
        1. Matrix Addition
        2. Matrix Subtraction
        3. Matrix Multiplication
        4. Matrix Transpose
        0. Exit

Features :
    - Validates numerical input using strtof()
    - Validates matrix dimensions
    - Supports integer and decimal matrix elements
    - Uses Variable Length Arrays (VLAs)
    - Checks mathematical conditions before performing operations

Matrix Rules :
    Addition/Subtraction:
        Both matrices must have the same order.

    Multiplication:
        Number of columns of Matrix A must equal
        number of rows of Matrix B.

    Transpose:
        An m × n matrix becomes an n × m matrix.

===============================================================================
*/


#include <stdio.h>
#include <stdlib.h>
#include <math.h>


/*
-------------------------------------------------------------------------------
                         NUMBER INPUT FUNCTION
-------------------------------------------------------------------------------

Purpose:
    Safely receives an integer or decimal number from the user.

Parameters:
    prompt        -> Message displayed before input.
    error_message -> Message displayed when input is invalid.

Returns:
    A valid floating-point number.

How it works:
    strtof() converts the input string into a float.
    The 'end' pointer tells us where the conversion stopped.

    Example:
        "25.5\n"  -> valid
        "abc\n"    -> invalid
        "25abc\n"  -> invalid

-------------------------------------------------------------------------------
*/

float get_number(const char *prompt, const char *error_message){

    char input[100];
    char *end;
    float value;

    while (1){

        printf("%s", prompt);

        fgets(input, sizeof(input), stdin);

        value = strtof(input, &end);

        /*
         * If conversion did not consume any characters,
         * the input was not a valid number.
         */
        if (end == input){
            printf("%s", error_message);
        }

        /*
         * After a valid number, the only expected character
         * is the newline generated by pressing Enter.
         *
         * Anything else means extra invalid input was entered.
         */
        else if (*end != '\n'){
            printf("%s", error_message);
        }

        else{
            return value;
        }
    }
}


/*
-------------------------------------------------------------------------------
                              MAIN MENU
-------------------------------------------------------------------------------

Purpose:
    Displays the available matrix operations and validates the user's choice.

Returns:
    0 -> Exit
    1 -> Addition
    2 -> Subtraction
    3 -> Multiplication
    4 -> Transpose

-------------------------------------------------------------------------------
*/

int main_menu(){

    float choice;

    while (1){

        choice = get_number(
            "\n1. Addition"
            "\n2. Subtraction"
            "\n3. Multiplication"
            "\n4. Transpose"
            "\n0. Exit"
            "\n\nEnter your choice >> ",

            "\nInvalid Input! Enter only 0-4.\n"
        );

        /*
         * Choice must:
         *  - be between 0 and 4
         *  - be a whole number
         */
        if (choice < 0 || choice > 4 || choice != floor(choice)){
            printf("\nInvalid Input! Enter only 0-4.\n");
        }

        else{
            return (int)choice;
        }
    }
}


/*
-------------------------------------------------------------------------------
                            MATRIX ADDITION
-------------------------------------------------------------------------------

Mathematical condition:

    A + B is possible only when:

        rows(A)    == rows(B)
        columns(A) == columns(B)

The result matrix has the same order as A and B.

-------------------------------------------------------------------------------
*/

void addition(
    int m, int n,
    int p, int q,
    float A[m][n],
    float B[p][q]
){

    float C[m][n];

    /*
     * Addition requires both matrices to have identical dimensions.
     */
    if (m == p && n == q){

        for (int i = 0; i < m; i++){

            for (int j = 0; j < n; j++){

                C[i][j] = A[i][j] + B[i][j];
            }
        }

        printf("\nA + B\n");

        for (int i = 0; i < 30; i++)
            printf("-");

        printf("\n\n");

        /*
         * Display the resulting matrix.
         */
        for (int i = 0; i < m; i++){

            printf("|  ");

            for (int j = 0; j < n; j++){
                printf("%6.2f\t", C[i][j]);
            }

            printf("|\n");
        }
    }

    else{

        printf(
            "\nAddition is not possible."
            "\nOrders of both matrices should be equal.\n"
        );
    }
}


/*
-------------------------------------------------------------------------------
                           MATRIX SUBTRACTION
-------------------------------------------------------------------------------

Mathematical condition:

    A - B is possible only when:

        rows(A)    == rows(B)
        columns(A) == columns(B)

-------------------------------------------------------------------------------
*/

void subtraction(
    int m, int n,
    int p, int q,
    float A[m][n],
    float B[p][q]
){

    float C[m][n];

    if (m == p && n == q){

        for (int i = 0; i < m; i++){

            for (int j = 0; j < n; j++){

                C[i][j] = A[i][j] - B[i][j];
            }
        }

        printf("\nA - B\n");

        for (int i = 0; i < 30; i++)
            printf("-");

        printf("\n\n");

        for (int i = 0; i < m; i++){

            printf("|  ");

            for (int j = 0; j < n; j++){
                printf("%6.2f\t", C[i][j]);
            }

            printf("|\n");
        }
    }

    else{

        printf(
            "\nSubtraction is not possible."
            "\nOrders of both matrices should be equal.\n"
        );
    }
}


/*
-------------------------------------------------------------------------------
                         MATRIX MULTIPLICATION
-------------------------------------------------------------------------------

Mathematical condition:

    A(m × n) × B(p × q)

    Multiplication is possible only when:

        n == p

    The resulting matrix has order:

        m × q

    Each element is calculated using:

        C[i][j] = Σ A[i][k] × B[k][j]

-------------------------------------------------------------------------------
*/

void multiplication(
    int m, int n,
    int p, int q,
    float A[m][n],
    float B[p][q]
){

    /*
     * Result dimensions are m × q,
     * NOT m × n.
     */
    float C[m][q];

    if (n == p){

        for (int i = 0; i < m; i++){

            for (int j = 0; j < q; j++){

                /*
                 * Start the sum at zero.
                 */
                C[i][j] = 0;

                /*
                 * Dot product of:
                 *     Row i of A
                 *     Column j of B
                 */
                for (int k = 0; k < n; k++){

                    C[i][j] += A[i][k] * B[k][j];
                }
            }
        }

        printf("\nA × B\n");

        for (int i = 0; i < 30; i++)
            printf("-");

        printf("\n\n");

        for (int i = 0; i < m; i++){

            printf("|  ");

            for (int j = 0; j < q; j++){
                printf("%6.2f\t", C[i][j]);
            }

            printf("|\n");
        }
    }

    else{

        printf(
            "\nMultiplication is not possible."
            "\nColumns of A must equal rows of B.\n"
        );
    }
}


/*
-------------------------------------------------------------------------------
                              TRANSPOSE
-------------------------------------------------------------------------------

Purpose:
    Converts an m × n matrix into an n × m matrix.

Rule:

        T[j][i] = A[i][j]

Example:

        A = | 1  2  3 |
            | 4  5  6 |

        Aᵀ = | 1  4 |
             | 2  5 |
             | 3  6 |

A separate matrix T is used because the dimensions change.

-------------------------------------------------------------------------------
*/

void transpose(int m, int n, float A[m][n]){

    /*
     * Original matrix:
     *
     *      m × n
     *
     * Transposed matrix:
     *
     *      n × m
     */
    float T[n][m];

    for (int i = 0; i < m; i++){

        for (int j = 0; j < n; j++){

            T[j][i] = A[i][j];
        }
    }

    printf("\nAᵀ\n");

    for (int i = 0; i < 30; i++)
        printf("-");

    printf("\n\n");

    for (int i = 0; i < n; i++){

        printf("|  ");

        for (int j = 0; j < m; j++){
            printf("%6.2f\t", T[i][j]);
        }

        printf("|\n");
    }
}


/*
-------------------------------------------------------------------------------
                         OPERATION CONTROLLER
-------------------------------------------------------------------------------

Purpose:
    Routes the selected menu option to the correct matrix operation.

This keeps main() cleaner and separates user-interface logic from
mathematical operations.

-------------------------------------------------------------------------------
*/

void operation(
    int choice,
    int m, int n,
    int p, int q,
    float A[m][n],
    float B[p][q]
){

    if (choice == 1){

        addition(m, n, p, q, A, B);
    }

    else if (choice == 2){

        subtraction(m, n, p, q, A, B);
    }

    else if (choice == 3){

        multiplication(m, n, p, q, A, B);
    }

    else if (choice == 4){

        transpose(m, n, A);
    }
}


/*
-------------------------------------------------------------------------------
                         MATRIX DIMENSION INPUT
-------------------------------------------------------------------------------

Purpose:
    Gets the number of rows and columns from the user.

Rules:
    - Must be positive.
    - Must be an integer.
    - Decimal dimensions are rejected.

-------------------------------------------------------------------------------
*/

void rows_columns(int *rows, int *columns){

    float row_value;

    while(1){

        row_value = get_number(
            "\nEnter the number of rows >> ",
            "\nInvalid Input! Enter a positive integer.\n"
        );

        if (row_value <= 0 || row_value != floor(row_value)){

            printf(
                "\nInvalid Input! Enter a positive integer.\n"
            );
        }

        else{

            *rows = row_value;
            break;
        }
    }


    float column_value;

    while(1){

        column_value = get_number(
            "\nEnter the number of columns >> ",
            "\nInvalid Input! Enter a positive integer.\n"
        );

        if (column_value <= 0 ||
            column_value != floor(column_value)){

            printf(
                "\nInvalid Input! Enter a positive integer.\n"
            );
        }

        else{

            *columns = column_value;
            break;
        }
    }
}


/*
-------------------------------------------------------------------------------
                           MATRIX INPUT FUNCTION
-------------------------------------------------------------------------------

Purpose:
    Receives every element of a matrix from the user.

Parameters:
    rows    -> Number of rows.
    columns -> Number of columns.
    mat     -> Matrix where values will be stored.
    name    -> Matrix identifier ('a' or 'b').

The function also displays the completed matrix.

-------------------------------------------------------------------------------
*/

void matrix(
    int rows,
    int columns,
    float mat[rows][columns],
    char name
){

    char prompt[50];

    for (int i = 0; i < rows; i++){

        for (int j = 0; j < columns; j++){

            /*
             * Generate prompts such as:
             *
             * Enter a11 >>
             * Enter a12 >>
             * Enter b11 >>
             */
            snprintf(
                prompt,
                sizeof(prompt),
                "\nEnter %c%d%d >> ",
                name,
                i + 1,
                j + 1
            );

            mat[i][j] = get_number(
                prompt,
                "\nInvalid Input! Enter an integer or decimal.\n"
            );
        }
    }

    printf("\n\n");

    /*
     * Display the entered matrix.
     */
    for (int i = 0; i < rows; i++){

        printf("|  ");

        for (int j = 0; j < columns; j++){

            printf("%6.2f\t", mat[i][j]);
        }

        printf("|\n");
    }

    printf("\n\n");
}


/*
===============================================================================
                                  MAIN
===============================================================================
*/

int main()
{
    int m, n, p, q, choice;

    /*
     * Program header.
     */
    for (int i = 0; i < 55; i++)
        printf("=");

    printf("\n");

    printf("\t\tMATRIX ENGINEERING TOOL\n");

    for (int i = 0; i < 55; i++)
        printf("=");

    printf("\n");


    /*
     * Ask the user which operation should be performed.
     */
    choice = main_menu();


    /*
     * EXIT
     */
    if (choice == 0){

        printf("\nExiting program...\n");

        return 0;
    }


    /*
     * TRANSPOSE
     *
     * Only Matrix A is required.
     */
    if (choice == 4){

        for (int i = 0; i < 55; i++)
            printf("-");

        printf("\n\n");

        printf("\t\t\tMATRIX A\n");

        for (int i = 0; i < 55; i++)
            printf("-");

        printf("\n\n");


        /*
         * Get dimensions of Matrix A.
         */
        rows_columns(&m, &n);

        /*
         * Variable Length Array:
         * dimensions are known at runtime.
         */
        float matrix_A[m][n];

        /*
         * Fill Matrix A.
         */
        matrix(m, n, matrix_A, 'a');

        /*
         * Perform transpose.
         */
        operation(
            choice,
            m, n,
            0, 0,
            matrix_A,
            NULL
        );
    }


    /*
     * ADDITION, SUBTRACTION, MULTIPLICATION
     *
     * Both Matrix A and Matrix B are required.
     */
    else if (choice == 1 ||
             choice == 2 ||
             choice == 3){

        /*
         * ---------------- MATRIX A ----------------
         */

        for (int i = 0; i < 55; i++)
            printf("-");

        printf("\n\n");

        printf("\t\t\tMATRIX A\n");

        for (int i = 0; i < 55; i++)
            printf("-");

        printf("\n\n");

        rows_columns(&m, &n);

        float matrix_A[m][n];

        matrix(m, n, matrix_A, 'a');


        /*
         * ---------------- MATRIX B ----------------
         */

        for (int i = 0; i < 55; i++)
            printf("-");

        printf("\n\n");

        printf("\t\t\tMATRIX B\n");

        for (int i = 0; i < 55; i++)
            printf("-");

        printf("\n\n");

        rows_columns(&p, &q);

        float matrix_B[p][q];

        matrix(p, q, matrix_B, 'b');


        /*
         * Perform the selected operation.
         *
         * The operation itself checks whether
         * the matrix dimensions are mathematically valid.
         */
        operation(
            choice,
            m, n,
            p, q,
            matrix_A,
            matrix_B
        );
    }


    return 0;
}